import { EOL } from 'os';
import { resolve } from 'path';
import { outputFile } from 'fs-extra';
import { format, resolveConfig } from 'prettier';
import { alternatives } from '@email-types/data/mso';
import * as log from './log';

const cwd = process.cwd();
const output = resolve(__dirname, '../src/data.ts');

const properties = Object.keys(alternatives).reduce<Record<string, string>>(
  (result, property) => {
    // split the mso alt property to get the matched css style
    // eg. `mso-line-height-alt` becomes `line-height`.
    const [, name] = property.split(/mso-|-alt/);
    result[name] = property;
    return result;
  },
  {},
);

const data = [
  '/* This file is automatically generated and should not be edited directly. */',
  `export const properties = ${JSON.stringify(properties)} as const;`,
].join(`${EOL}${EOL}`);

(async (): Promise<void> => {
  try {
    log.info('generating data');

    log.wait('formatting...');
    const config = await resolveConfig(cwd);
    const content = format(data, {
      ...config,
      parser: 'typescript',
    });

    await outputFile(output, content.replace(/\n/g, EOL));

    log.done('successfully generated data');
  } catch (err) {
    log.error(err);
    process.exit(0);
  }
})();
